# Generated by Django 3.2.18 on 2023-05-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='mysite\x0cood\\static\x0cood\\img\\image.jpg', max_length=500),
        ),
    ]
